# Recommended lints for Flutter apps, packages, and plugins.
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  errors:
    # Treat missing returns as a warning (not a hint).
    missing_return: warning
  exclude:
    - "lib/**/*.g.dart"

linter:
  rules:
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_final_fields: true
    prefer_final_locals: true
    always_specify_types: true
    prefer_single_quotes: true
    always_declare_return_types: true
